profiles:
  local_resiliency:
    env_script: ./env/bootstrap.example.sh
    env:
      GERYON_SITE: local_resiliency
    defaults:
      run_local:
        executor: process
        max_concurrent_tasks: 4
        cores_per_task: 1
        command_timeout_sec: 2
        max_retries: 1
        retry_on_status: [failed, terminated]
        max_failures: 4
        resume: true
        progress: true

  slurm_demo:
    partition: debug
    time_min: 20
    cpus_per_task: 4
    mem_gb: 8
    gpus_per_node: 0
    job_name: ex04_resilience
    defaults:
      run_slurm:
        executor: process
        max_concurrent_tasks: 4
        cores_per_task: 1
        batches_per_task: 1
        query_status: true
