profiles:
  local_fail_fast:
    env_script: ./env/bootstrap.example.sh
    env:
      GERYON_SITE: local_recovery_initial
    defaults:
      run_local:
        executor: process
        max_concurrent_tasks: 2
        command_timeout_sec: 2
        max_retries: 0
        retry_on_status: [failed, terminated]
        max_failures: 2
        resume: true

  local_recover:
    env_script: ./env/bootstrap.example.sh
    env:
      GERYON_SITE: local_recovery_rerun
    defaults:
      run_local:
        executor: process
        max_concurrent_tasks: 2
        command_timeout_sec: 6
        max_retries: 0
        retry_on_status: [failed, terminated]
        resume: true
        progress: true

  slurm_demo:
    partition: debug
    time_min: 20
    cpus_per_task: 2
    mem_gb: 8
    gpus_per_node: 0
    job_name: ex05_recovery
    defaults:
      run_slurm:
        executor: process
        max_concurrent_tasks: 2
        cores_per_task: 1
        batches_per_task: 1
        query_status: true
