schema:
  version: 4
command:
  program: python3
  args:
    - ../../common/dummy_hydra_app.py
select:
  packs:
    - name: architecture
      options:
        - id: resnet18
          params:
            model:
              family: cnn
              name: resnet18
        - id: vit_tiny
          params:
            model:
              family: transformer
              name: vit_tiny
        - id: mlp_large
          params:
            model:
              family: mlp
              name: mlp
              width: 512
              depth: 6
    - name: hparam_profile
      options:
        - id: cnn_profile
          params:
            train:
              lr: 0.001
              weight_decay: 0.0005
              optimizer: adam
        - id: vit_profile
          params:
            train:
              lr: 0.0003
              weight_decay: 0.05
              optimizer: adamw
        - id: mlp_profile
          params:
            train:
              lr: 0.0007
              weight_decay: 0.001
              optimizer: adamw
    - name: seed
      options:
        - id: seed1
          params:
            seed: 1
        - id: seed2
          params:
            seed: 2
constraints:
  predicates:
    - id: profile_matches_arch
      args:
        arch:
          pack_id: architecture
        profile:
          pack_id: hparam_profile
      expr:
        or:
          - and:
              - eq: ["$arch", "resnet18"]
              - eq: ["$profile", "cnn_profile"]
          - and:
              - eq: ["$arch", "vit_tiny"]
              - eq: ["$profile", "vit_profile"]
          - and:
              - eq: ["$arch", "mlp_large"]
              - eq: ["$profile", "mlp_profile"]
    - id: lr_guardrails
      args:
        arch:
          pack_id: architecture
        lr:
          param: train.lr
      expr:
        or:
          - and:
              - eq: ["$arch", "resnet18"]
              - between: ["$lr", 0.0005, 0.002]
          - and:
              - eq: ["$arch", "vit_tiny"]
              - between: ["$lr", 0.0001, 0.0005]
          - and:
              - eq: ["$arch", "mlp_large"]
              - between: ["$lr", 0.0003, 0.001]
defaults:
  params:
    data:
      dataset: cifar100
    train:
      epochs: 100
