profiles:
  local_merge:
    env_script: ./env/bootstrap.example.sh
    env:
      GERYON_SITE: local_merge_policies
    defaults:
      run_local:
        executor: process
        max_concurrent_tasks: 2

  slurm_demo:
    partition: debug
    time_min: 20
    cpus_per_task: 2
    mem_gb: 8
    gpus_per_node: 0
    job_name: merge_policy_demo
    defaults:
      run_slurm:
        executor: process
        max_concurrent_tasks: 2
        cores_per_task: 1
        batches_per_task: 1
        query_status: true
