profiles:
  local_throughput:
    env_script: ./env/bootstrap.example.sh
    env:
      GERYON_SITE: local_constraints
    defaults:
      run_local:
        executor: process
        max_concurrent_tasks: 4

  slurm_demo:
    partition: debug
    time_min: 20
    cpus_per_task: 4
    mem_gb: 8
    gpus_per_node: 0
    job_name: ex02_constraints
    defaults:
      run_slurm:
        executor: process
        max_concurrent_tasks: 4
        cores_per_task: 1
        batches_per_task: 1
        query_status: true
