schema:
  version: 4
command:
  program: python3
  args:
    - ../../common/dummy_hydra_app.py
select:
  packs:
    - name: seed
      options:
        - id: seed1
          params:
            seed: 1
        - id: seed2
          params:
            seed: 2
        - id: seed3
          params:
            seed: 3
    - name: lr
      options:
        - id: lr1e3
          params:
            train:
              lr: 0.001
        - id: lr3e4
          params:
            train:
              lr: 0.0003
        - id: lr1e4
          params:
            train:
              lr: 0.0001
    - name: weight_decay
      options:
        - id: wd0
          params:
            train:
              weight_decay: 0.0
        - id: wd1e2
          params:
            train:
              weight_decay: 0.01
    - name: batch_size
      options:
        - id: bs64
          params:
            train:
              batch_size: 64
        - id: bs128
          params:
            train:
              batch_size: 128
defaults:
  params:
    model:
      name: mlp
      width: 256
      depth: 4
